using System;
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace mvcExpress.Editor.Core
{
#if !MVC_EXPRESS_NO_ATTRIBUTE
    /// <summary>
    /// Bakes [CatalogPrefab]-marked Mediator prefabs into a generated ViewPrefabCatalog before every
    /// Play Mode entry, cancelling entry if the scan finds any orphaned/duplicate mapping.
    /// </summary>
    [InitializeOnLoad]
    internal static class MvcCatalogPrefabBaker
    {
        /// <summary>Folder the baker creates on first use to hold the generated catalog asset.</summary>
        internal const string GeneratedCatalogFolder = "Assets/mvcExpress/Generated";

        /// <summary>
        /// Asset path of the auto-generated catalog. Also read by <see cref="mvcExpress.Editor.Inspectors.MvcPrefabCatalogEditor"/>
        /// to show the "auto-generated, do not hand-edit" notice on this specific asset.
        /// </summary>
        internal const string GeneratedCatalogPath = GeneratedCatalogFolder + "/AutoGenerated_ViewPrefabCatalog.asset";

        static MvcCatalogPrefabBaker()
        {
            EditorApplication.playModeStateChanged += OnPlayModeStateChanged;
        }

        private static void OnPlayModeStateChanged(PlayModeStateChange state)
        {
            if (state != PlayModeStateChange.ExitingEditMode)
                return;

            var result = MvcCatalogPrefabGatherer.Scan();
            bool catalogExists = AssetDatabase.LoadAssetAtPath<ViewPrefabCatalog>(GeneratedCatalogPath) != null;

            if (result.ValidMappings.Count == 0 && !result.HasErrors && !catalogExists)
                return; // Nothing marked, nothing previously baked - nothing to do.

            if (!MvcCompositionStyleSettings.IsSoftAllowed(MvcCompositionStyle.Attribute))
            {
                MvcCompositionStyleWarning.WarnIfDisabled(MvcCompositionStyle.Attribute, "[CatalogPrefab] baking");
            }

            if (result.HasErrors)
            {
                for (int i = 0; i < result.Errors.Count; i++)
                    Debug.LogError($"[mvcExpress] {result.Errors[i]}");

                Debug.LogError("[mvcExpress] [CatalogPrefab] baking failed - cancelling Play Mode entry. Fix the errors above and try again.");
                EditorApplication.isPlaying = false;
                return;
            }

            var facades = FindFacadesInLoadedScenes();
            if (facades.Length > 1)
            {
                Debug.LogError(
                    $"[mvcExpress] [CatalogPrefab] baking found {facades.Length} MvcFacade instances in the current scene(s) - " +
                    "only one MvcFacade may exist at a time. Cancelling Play Mode entry.");
                EditorApplication.isPlaying = false;
                return;
            }

            var catalog = LoadOrCreateGeneratedCatalog();
            if (!CatalogMatches(catalog, result.ValidMappings))
            {
                MvcCatalogPrefabWriter.Write(catalog, result.ValidMappings);
                EditorUtility.SetDirty(catalog);
                AssetDatabase.SaveAssets();
            }

            if (facades.Length == 1)
            {
                WireCatalogToFacade(facades[0], catalog);
            }
        }

        private static MvcFacade[] FindFacadesInLoadedScenes()
        {
#if UNITY_6000_5_OR_NEWER
            return UnityEngine.Object.FindObjectsByType<MvcFacade>(FindObjectsInactive.Include);
#elif UNITY_2023_1_OR_NEWER
#pragma warning disable CS0618 // FindObjectsSortMode: deprecated in 6000.5, required before it
            return UnityEngine.Object.FindObjectsByType<MvcFacade>(FindObjectsInactive.Include, FindObjectsSortMode.None);
#pragma warning restore CS0618
#else
#pragma warning disable CS0618 // FindObjectsOfType: pre-2023.1 API
            return UnityEngine.Object.FindObjectsOfType<MvcFacade>(true);
#pragma warning restore CS0618
#endif
        }

        private static ViewPrefabCatalog LoadOrCreateGeneratedCatalog()
        {
            var existing = AssetDatabase.LoadAssetAtPath<ViewPrefabCatalog>(GeneratedCatalogPath);
            if (existing != null)
                return existing;

            if (!AssetDatabase.IsValidFolder(GeneratedCatalogFolder))
            {
                if (!AssetDatabase.IsValidFolder("Assets/mvcExpress"))
                    AssetDatabase.CreateFolder("Assets", "mvcExpress");
                AssetDatabase.CreateFolder("Assets/mvcExpress", "Generated");
            }

            var created = ScriptableObject.CreateInstance<ViewPrefabCatalog>();
            AssetDatabase.CreateAsset(created, GeneratedCatalogPath);
            return created;
        }

        // Avoids an unconditional SetDirty/SaveAssets (and the disk write/VCS noise that comes with
        // it) on every single Play Mode entry when the bake produced exactly what's already there.
        private static bool CatalogMatches(ViewPrefabCatalog catalog, List<CatalogPrefabMapping> mappings)
        {
            var existing = catalog.MediatorPrefabs;
            if (existing == null || existing.Length != mappings.Count)
                return false;

            for (int i = 0; i < mappings.Count; i++)
            {
                var mapping = mappings[i];
                var entry = existing[i];
                if (entry == null
                    || entry.Prefab != mapping.Prefab
                    || entry.MediatorTypeName != mapping.MediatorType.AssemblyQualifiedName)
                {
                    return false;
                }
            }

            return true;
        }

        private static void WireCatalogToFacade(MvcFacade facade, ViewPrefabCatalog catalog)
        {
            var catalogs = facade.ViewPrefabCatalogs ?? Array.Empty<ViewPrefabCatalog>();
            if (Array.IndexOf(catalogs, catalog) >= 0)
                return;

            var updated = new ViewPrefabCatalog[catalogs.Length + 1];
            catalogs.CopyTo(updated, 0);
            updated[catalogs.Length] = catalog;
            facade.ViewPrefabCatalogs = updated;

            EditorUtility.SetDirty(facade);
            EditorSceneManager.MarkSceneDirty(facade.gameObject.scene);
        }
    }
#endif
}
